CREATE TYPE page_status as enum('P','R','F');

CREATE UNLOGGED TABLE IF NOT EXISTS page (
  id_page TEXT NOT NULL,
  name TEXT NOT NULL,
  token TEXT NOT NULL,
  date_created TIMESTAMP(0) NOT NULL DEFAULT NOW(),
  date_run_start TIMESTAMP(0) NULL,
  date_run_end TIMESTAMP(0) NULL,
  status page_status,
  PRIMARY KEY (id_page))
;

-- -----------------------------------------------------
-- Table page_data
-- -----------------------------------------------------

CREATE UNLOGGED TABLE IF NOT EXISTS page_data (
  id_page TEXT NOT NULL,
  year_data BIGINT,
  month_data BIGINT,
  date_data DATE,
  fans BIGINT,
  fans_country JSON,
  fans_city JSON,
  fans_by_like_source_unique_ads BIGINT,
  fans_by_like_source_unique_news_feed BIGINT,
  fans_by_like_source_unique_other BIGINT,
  fans_by_like_source_unique_page_suggestions BIGINT,
  fans_by_like_source_unique_restored_likes BIGINT,
  fans_by_like_source_unique_search BIGINT,
  fans_by_like_source_unique_your_page BIGINT,
  fans_by_like_source_ads BIGINT,
  fans_by_like_source_news_feed BIGINT,
  fans_by_like_source_other BIGINT,
  fans_by_like_source_page_suggestions BIGINT,
  fans_by_like_source_restored_likes BIGINT,
  fans_by_like_source_search BIGINT,
  fans_by_like_source_your_page BIGINT,
  impressions BIGINT,
  impressions_unique BIGINT,
  impressions_28_days BIGINT,
  impressions_unique_28_days BIGINT,
  impressions_organic_unique BIGINT,
  impressions_organic_unique_28_days BIGINT,
  impressions_paid_unique BIGINT,
  impressions_paid_unique_28_days BIGINT,
  impressions_viral_unique BIGINT,
  impressions_viral_unique_28_days BIGINT,
  impressions_organic BIGINT,
  impressions_organic_28_days BIGINT,
  impressions_paid BIGINT,
  impressions_paid_28_days BIGINT,
  impressions_viral BIGINT,
  impressions_viral_28_days BIGINT,
  impressions_by_story_unique_mention BIGINT,
  impressions_by_story_unique_other BIGINT,
  impressions_by_story_unique_fan BIGINT,
  impressions_by_story_unique_page_post BIGINT,
  impressions_by_story_unique_checkin BIGINT,
  impressions_by_story_mention BIGINT,
  impressions_by_story_other BIGINT,
  impressions_by_story_fan BIGINT,
  impressions_by_story_page_post BIGINT,
  impressions_by_story_checkin BIGINT,
  impressions_by_country JSON,
  impressions_by_city JSON,
  impressions_by_age_gender_unique_F_13_17 BIGINT,
  impressions_by_age_gender_unique_F_18_24 BIGINT,
  impressions_by_age_gender_unique_F_25_34 BIGINT,
  impressions_by_age_gender_unique_F_35_44 BIGINT,
  impressions_by_age_gender_unique_F_45_54 BIGINT,
  impressions_by_age_gender_unique_F_55_64 BIGINT,
  impressions_by_age_gender_unique_F_65 BIGINT,
  impressions_by_age_gender_unique_M_13_17 BIGINT,
  impressions_by_age_gender_unique_M_18_24 BIGINT,
  impressions_by_age_gender_unique_M_25_34 BIGINT,
  impressions_by_age_gender_unique_M_35_44 BIGINT,
  impressions_by_age_gender_unique_M_45_54 BIGINT,
  impressions_by_age_gender_unique_M_55_64 BIGINT,
  impressions_by_age_gender_unique_M_65 BIGINT,
  impressions_by_age_gender_unique_U_13_17 BIGINT,
  impressions_by_age_gender_unique_U_18_24 BIGINT,
  impressions_by_age_gender_unique_U_25_34 BIGINT,
  impressions_by_age_gender_unique_U_35_44 BIGINT,
  impressions_by_age_gender_unique_U_45_54 BIGINT,
  impressions_by_age_gender_unique_U_55_64 BIGINT,
  impressions_by_age_gender_unique_U_65 BIGINT,
  engaged_users BIGINT,
  consumptions_by_type_unique_video_play BIGINT,
  consumptions_by_type_unique_other_clicks BIGINT,
  consumptions_by_type_unique_photo_view BIGINT,
  consumptions_by_type_unique_link_clicks BIGINT,
  consumptions_by_type_video_play BIGINT,
  consumptions_by_type_other_clicks BIGINT,
  consumptions_by_type_photo_view BIGINT,
  consumptions_by_type_link_clicks BIGINT,
  places_checkin BIGINT,
  negative_feedback_by_type_unique_hide_all_clicks BIGINT,
  negative_feedback_by_type_unique_hide_clicks BIGINT,
  negative_feedback_by_type_unique_unlike_page_clicks BIGINT,
  negative_feedback_by_type_unique_report_spam_clicks BIGINT,
  negative_feedback_by_type_hide_all_clicks BIGINT,
  negative_feedback_by_type_hide_clicks BIGINT,
  negative_feedback_by_type_unlike_page_clicks BIGINT,
  negative_feedback_by_type_report_spam_clicks BIGINT,
  positive_feedback_by_type_unique_link BIGINT,
  positive_feedback_by_type_unique_like BIGINT,
  positive_feedback_by_type_unique_comment BIGINT,
  positive_feedback_by_type_unique_other BIGINT,
  positive_feedback_by_type_link BIGINT,
  positive_feedback_by_type_like BIGINT,
  positive_feedback_by_type_comment BIGINT,
  positive_feedback_by_type_other BIGINT,
  reactions_like BIGINT,
  reactions_love BIGINT,
  reactions_wow BIGINT,
  reactions_haha BIGINT,
  reactions_sorry BIGINT,
  reactions_anger BIGINT,
  date_created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_page, date_data, date_created)
 ,
  CONSTRAINT fk_page_id
    FOREIGN KEY (id_page)
    REFERENCES page (id_page)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

-- -----------------------------------------------------
-- Table post_data
-- -----------------------------------------------------

CREATE UNLOGGED TABLE IF NOT EXISTS post_data (
  post_id TEXT NOT NULL,
  id_page TEXT NOT NULL,
  year_data SMALLINT,
  month_data SMALLINT,
  comment_num INTEGER,
  date_created TIMESTAMP NOT NULL DEFAULT NOW(),
  post_created_time TIMESTAMP,
  post_name TEXT,
  post_type TEXT,
  post_message TEXT,
  post_link TEXT,
  is_hidden BOOLEAN,
  activity BIGINT,
  activity_by_action_type_comment BIGINT,
  activity_by_action_type_like BIGINT,
  activity_by_action_type_share BIGINT,
  activity_by_action_type_unique_comment BIGINT,
  activity_by_action_type_unique_like BIGINT,
  activity_by_action_type_unique_share BIGINT,
  activity_unique BIGINT,
  clicks BIGINT,
  clicks_by_type_link BIGINT,
  clicks_by_type_other BIGINT,
  clicks_by_type_video_play BIGINT,
  clicks_unique BIGINT,
  engaged_users BIGINT,
  impressions BIGINT,
  impressions_fan BIGINT,
  impressions_fan_unique BIGINT,
  impressions_unique BIGINT,
  negative_feedback BIGINT,
  negative_feedback_unique BIGINT,
  page_engaged_users BIGINT,
  post_impressions_organic BIGINT,
  post_impressions_organic_unique BIGINT,
  post_impressions_paid BIGINT,
  post_impressions_paid_unique BIGINT,
  post_impressions_viral BIGINT,
  reactions_anger BIGINT,
  reactions_haha BIGINT,
  reactions_like BIGINT,
  reactions_love BIGINT,
  reactions_sorry BIGINT,
  reactions_wow BIGINT,
  video_avg_time_watched BIGINT,
  video_complete_views_organic BIGINT,
  video_complete_views_organic_unique BIGINT,
  video_organic_unique BIGINT,
  video_view_time BIGINT,
  video_views BIGINT,
  video_views_organic BIGINT,
  video_views_organic_unique BIGINT,
  video_views_unique BIGINT,
  video_complete_views_paid BIGINT,
  video_complete_views_paid_unique BIGINT,
  video_complete_views_30s_autoplayed BIGINT,
  video_complete_views_30s_clicked_to_play BIGINT,
  video_retention_graph_autoplayed JSON,
  video_views_autoplayed BIGINT,
  video_retention_graph JSON,
  video_retention_graph_clicked_to_play JSON,
  video_views_paid BIGINT,
  video_views_paid_unique BIGINT,
  video_length BIGINT,
  video_views_clicked_to_play BIGINT,
  video_views_10s BIGINT,
  video_views_10s_unique BIGINT,
  video_views_10s_autoplayed BIGINT,
  video_views_10s_clicked_to_play BIGINT,
  video_views_10s_organic BIGINT,
  video_views_10s_paid BIGINT,
  video_views_10s_sound_on BIGINT,
  video_views_sound_on BIGINT,
  video_view_time_organic BIGINT,
  video_view_time_by_age_bucket_and_gender JSON,
  video_view_time_by_region_id JSON,
  video_views_by_distribution_type JSON,
  video_view_time_by_distribution_type JSON,
  video_view_time_by_country_id JSON,
  PRIMARY KEY (post_id, date_created)
 ,
  CONSTRAINT fk_page_id_post
    FOREIGN KEY (id_page)
    REFERENCES page (id_page)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE UNLOGGED TABLE IF NOT EXISTS post_comment_data (
  comment_id TEXT NOT NULL,
  post_id TEXT NOT NULL,
  message TEXT,
  comment_created_time TIMESTAMP,
  date_created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (comment_id)
);

CREATE UNLOGGED TABLE conversation (
  conversation_id TEXT NOT NULL,
  id_page TEXT NOT NULL,
  message_count INT NOT NULL,
  updated_time TEXT NOT NULL,
  link TEXT NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (conversation_id) ,
  CONSTRAINT fk_page_id_conversation
    FOREIGN KEY (id_page)
    REFERENCES page (id_page)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE UNLOGGED TABLE message (
  message_id TEXT NOT NULL,
  conversation_id TEXT NOT NULL,
  from_id TEXT NOT NULL,
  from_email TEXT NOT NULL,
  from_name TEXT NOT NULL,
  message TEXT NULL,
  sticker TEXT NULL,
  message_created_time TIMESTAMP NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (message_id),
  CONSTRAINT fk_page_id_message
    FOREIGN KEY (conversation_id)
    REFERENCES conversation (conversation_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)